server:
  port: 1112
spring:
  rabbitmq:
    host: 132.232.96.97
    port: 5672
    username: admin
    password: admin
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    registry-fetch-interval-seconds: 10
